server:
  port: 6002
  context-path: /
spring:
  application:
    name: process
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/flow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: songyz
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /statics/**
    throw-exception-if-no-handler-found: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    com.itmuch: INFO
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9871/eureka