spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: songyz
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true